app:
  port: 3002
  caching:
    ttl: 5
    max: 1000
  auth:
    enableJwtAuth: false,
    enableSessionAuth: false,
    jwtSettings:
      secret: 'eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hYXNfcHJvZF8yMDIwMDMyNiIsInR5cCI6IkpXVCJ9'

    # strategies:
    #   facebook:
    #     clientID: 'gfgfggfgfgfgf'
    #     clientSecret: 'fgfgfgfgf'
    #     fbGraphVersion: 'v3.0'
    #     callbackURL: 'https://142fa311.ngrok.io/account/facebook/callback'
    #   github:
    #     clientID: 'gfgfgfgfgfgf'
    #     clientSecret: 'gfgfgfgfgfgfgfg'
    #     fbGraphVersion: 'v3.0'
    #     callbackURL: 'https://142fa311.ngrok.io/account/github/callback'
    #   google:
    #     clientID: 'fgffgfgfg'
    #     clientSecret: 'fgfgfgfgfggf'
    #     fbGraphVersion: 'v3.0'
    #     callbackURL: 'https://142fa311.ngrok.io/account/google/callback'

database:
  postgres:
    uri: mongodb://postgres:5432/
    name: ezyfs
    options: ''

  redis:
    host: 'redis'
    port: '6379'
    password: ''
